experiment:
  name: "heat_demand_prediction"
  version: "v1.0"
  description: "클러스터별 열 수요 예측"

data:
  dataset_name: "heat"
  target_column: "heat_demand"
  data_path: "data"
  
cluster:
  mapping:
    0: ['E', 'F', 'I', 'J', 'K', 'N', 'O', 'Q']
    1: ['B', 'C', 'G']
    2: ['A', 'D', 'H', 'P']
    3: ['L', 'M', 'R', 'S']

split:
  type: "random"  # "random" or "time"
  test_size: 0.2
  random_state: 42
  time_split:
    holdout_start: 2023070101
    holdout_end: 2023123123

training:
  models: ["XGB"]
  tune_hyperparams: true
  n_trials: 20
  early_stopping_rounds: 50
  prophet_params:
    growth: 'linear'
    seasonality_mode: 'additive'
    yearly_seasonality: True
    weekly_seasonality: True
  
logging:
  level: "INFO"
  save_plots: true
  save_metrics: true
  log_dir: "logs"
  plots_dir: "plots"
  results_dir: "results"
