device: gpu
gpu_platform_id: 0
gpu_device_id: 0
colsample_bytree: 0.9
metric: mae
learning_rate: 0.08
n_estimators: 500
num_leaves: 2000
max_depth: 15
min_child_samples: 5
min_child_weight: 1e-5
random_state: 42